### ISSUE TITLE
Plans for the xstate svelte library

### ISSUE THREAD

**Issue by colinbate** [timdeschryver/svelte-utils#4]
Hi, @timdeschryver I came across this repo when looking for integrations of XState with Svelte. I see what you've done here and it looks good, but I wasn't sure what your plans were for the package given its early pre-release status.

I'm personally just starting out on my XState journey, but I'm interested in using it in my next Svelte app and just wanted to gauge how stable this library is. Thanks

**Comment by timdeschryver** [comment]
Hi @colinbate the plan is to follow svelte's and xstate's releases and keep this library in sync with the xstate react (hooks) package. I'm aware that it's missing documentation at the moment, as a reference you can take a look at tests. I'm not sure when I would want to write some documtation for it because I'm not sure how many people will use the library (feel free to contribute if you want!).

I'm currently using the machine store on [my blog](https://github.com/timdeschryver/timdeschryver.dev/blob/master/src/routes/blog/%5Bslug%5D.svelte#L23).

I hope this answers your question, feel free to ask more details or some help to implement it.
